
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shantanu
 */
public class Reg_admin extends javax.swing.JFrame {

    /**
     * Creates new form UserInfo
     */
    public Reg_admin() {
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int x=900;
        int y=600;
        this.setSize(x,y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PhoneNo = new javax.swing.JTextField();
        FirstName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        MiddleName = new javax.swing.JTextField();
        DOB = new javax.swing.JTextField();
        NationalId = new javax.swing.JTextField();
        BirthCertificateNo = new javax.swing.JTextField();
        PresentAddress = new javax.swing.JTextField();
        PermanentAddress = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        ReferanceId = new javax.swing.JTextField();
        SignUp = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Phone No");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 160, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 140, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 80, 120, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Middle Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 110, 150, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("DOB");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 140, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("National Id");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 180, 170, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Birth Certificate");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 220, 170, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Present Address");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 260, 190, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Permanent Address");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 310, 190, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Password");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 350, 150, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Referance id");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 410, 160, 22);
        getContentPane().add(PhoneNo);
        PhoneNo.setBounds(250, 12, 410, 30);
        getContentPane().add(FirstName);
        FirstName.setBounds(250, 50, 411, 22);
        getContentPane().add(LastName);
        LastName.setBounds(250, 80, 411, 22);
        getContentPane().add(MiddleName);
        MiddleName.setBounds(250, 110, 411, 22);
        getContentPane().add(DOB);
        DOB.setBounds(250, 140, 411, 22);
        getContentPane().add(NationalId);
        NationalId.setBounds(250, 180, 411, 22);
        getContentPane().add(BirthCertificateNo);
        BirthCertificateNo.setBounds(250, 220, 411, 22);
        getContentPane().add(PresentAddress);
        PresentAddress.setBounds(250, 260, 411, 22);
        getContentPane().add(PermanentAddress);
        PermanentAddress.setBounds(250, 300, 411, 22);
        getContentPane().add(Password);
        Password.setBounds(250, 350, 411, 22);
        getContentPane().add(ReferanceId);
        ReferanceId.setBounds(250, 410, 411, 22);

        SignUp.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        SignUp.setText("Sign Up");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        getContentPane().add(SignUp);
        SignUp.setBounds(260, 480, 150, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(711, 487, 160, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        
    Connection connection;
    PreparedStatement pst;
    ResultSet result = null, stockResult;
  try {
   
   //connection Establishment
   connection=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=MFS","sa","ra123456");
   pst=connection.prepareStatement("insert into UserInfo values(?,?,?,?,?,?,?,?,?,?,?,?)");
   pst.setInt(1,Integer.parseInt(PhoneNo.getText()));
   int phone = Integer.parseInt(PhoneNo.getText());
   pst.setString(2, FirstName.getText());
   pst.setString(3, LastName.getText());
   pst.setString(4, MiddleName.getText());
   pst.setString(5, DOB.getText());
   pst.setString(6, NationalId.getText());
   pst.setString(7, BirthCertificateNo.getText());
   pst.setString(8, PresentAddress.getText());
   pst.setString(9, PermanentAddress.getText());
   pst.setString(10, Password.getText());
   pst.setString(11, ReferanceId.getText());
   pst.setInt(12,3);
  
   pst.executeUpdate();
   
   PhoneNo.setText(" ");
   FirstName.setText(" ");
   FirstName.setText(" ");
   LastName.setText(" ");
   MiddleName.setText(" ");
   DOB.setText(" ");
   NationalId.setText(" ");
   BirthCertificateNo.setText(" ");
   PresentAddress.setText(" ");
   PermanentAddress.setText(" ");
   Password.setText(" ");
   ReferanceId.setText(" ");
   
      
      JOptionPane.showMessageDialog(null, "Registration successful");
      Login_Signup one = new Login_Signup();
      one.setVisible(true);
      dispose();
   

  }
  catch(SQLException e) {
   JOptionPane.showMessageDialog(null, "Registration not successful");
  } 
        
    }//GEN-LAST:event_SignUpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Account_Info_admin one =new Account_Info_admin();
        one.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BirthCertificateNo;
    private javax.swing.JTextField DOB;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField MiddleName;
    private javax.swing.JTextField NationalId;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField PermanentAddress;
    private javax.swing.JTextField PhoneNo;
    private javax.swing.JTextField PresentAddress;
    private javax.swing.JTextField ReferanceId;
    private javax.swing.JButton SignUp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
